name: CycloneDX .NET Generate SBOM

on:
  push:
    branches:
      - main # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Adjust to your project's .NET version        

      - name: CycloneDX .NET Generate SBOM
        uses: CycloneDX/gh-dotnet-generate-sbom@v1.0.1
        with:
          path: ./*.sln
          out: "./ObsoleteEncryptionConsoleApp/sbom-gen.xml"

      - name: Upload BOM
        uses: actions/upload-artifact@v2
        with:
          name: bom
          path: ./ObsoleteEncryptionConsoleApp/sbom.xml     
