name: CycloneDX .NET Generate SBOM

on:
  push:
    branches:
      - main # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Adjust to your project's .NET version        
          
      - name: Build and Generate CycloneDX BOM
        run: |
          dotnet build --configuration Release
          dotnet CycloneDX . -o ${{ github.workspace }}/bom.xml
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Upload BOM
        uses: actions/upload-artifact@v2
        with:
          name: bom
          path: ${{ github.workspace }}/bom.xml
